### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eranjo**
URLLIB3 installation included

### CODE REVIEW

**Comment by gazoodle** [comment]
Hmm, that's what the lines
```
install_requires =
    urllib3
```
in setup.cfg ought to do. I'll investigate why this didn't happen ...

**Comment by eranjo** [comment]
I see this error message without urllib3 being installed manually.


 eranjo-mbp:~ eranjo$ pip install geckolib
Collecting geckolib
  Using cached geckolib-0.3.15-py3-none-any.whl (63 kB)
Installing collected packages: geckolib
Successfully installed geckolib-0.3.15
eranjo-mbp:~ eranjo$ python3
Python 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from geckolib import GeckoShell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/geckolib/__init__.py", line 6, in <module>
    from .automation import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/geckolib/automation/__init__.py", line 3, in <module>
    from .base import GeckoAutomationBase
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/geckolib/automation/base.py", line 3, in <module>
    from ..driver import Observable
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/geckolib/driver/__init__.py", line 20, in <module>
    from .spapack import GeckoSpaPack
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/geckolib/driver/spapack.py", line 4, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
>>>

**Comment by gazoodle** [comment]
Can you try 0.3.17. I think I had the requirements in the wrong section of the setup.cfg file.

**Comment by eranjo** [comment]
0.3.17 fixed the issue!

**Comment by gazoodle** [comment]
> 0.3.17 fixed the issue!

Phew! Thanks for testing

**Pull request closed without merging**
